services:
    ocarat_core.order:
        class: Ocarat\CoreBundle\Service\Order
        arguments: ["@doctrine"]

    ocarat_core.stats:
        class: Ocarat\CoreBundle\Service\Stats
        arguments: ["@doctrine"]

    ocarat_core.legacyManager:
        class: Ocarat\CoreBundle\Service\LegacyManager
        arguments: ["@doctrine"]
    ocarat.product.search.manager:
         class: Ocarat\CoreBundle\Service\ProductSearchManager
         arguments: ["@doctrine"]